
// This file has been generated by the GUI designer. Do not modify.
namespace EliAssaltoAnfibio
{
	public partial class EliOptions
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label1;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.VBox vbox7;
		private global::Gtk.HSeparator hseparator7;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Button button1;
		private global::Gtk.Entry entry1;
		private global::Gtk.Label label4;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button button2;
		private global::Gtk.HScale hscale1;
		private global::Gtk.Label label5;
		private global::Gtk.HSeparator hseparator5;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button button3;
		private global::Gtk.HScale hscale2;
		private global::Gtk.Label label6;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.VBox vbox4;
		private global::Gtk.VBox vbox6;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button button5;
		private global::Gtk.HScale hscale4;
		private global::Gtk.Label label8;
		private global::Gtk.HSeparator hseparator6;
		private global::Gtk.VBox vbox11;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Button button13;
		private global::Gtk.HScale hscale5;
		private global::Gtk.Label label3;
		private global::Gtk.HSeparator hseparator11;
		private global::Gtk.HBox hbox12;
		private global::Gtk.Button button14;
		private global::Gtk.HScale hscale6;
		private global::Gtk.Label label11;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Button button6;
		private global::Gtk.HScale hscale7;
		private global::Gtk.Label label9;
		private global::Gtk.HSeparator hseparator13;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Button button4;
		private global::Gtk.HScale hscale3;
		private global::Gtk.Label label10;
		private global::Gtk.VBox vbox10;
		private global::Gtk.HSeparator hseparator12;
		private global::Gtk.HBox hbox7;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button button10;
		private global::Gtk.Button button15;
		private global::Gtk.Button button16;
		private global::Gtk.Button button17;
		private global::Gtk.HSeparator hseparator10;
		private global::Gtk.VBox vbox8;
		private global::Gtk.VBox vbox9;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Button button8;
		private global::Gtk.Button button11;
		private global::Gtk.Button button9;
		private global::Gtk.Button button12;
		private global::Gtk.Button button7;
		private global::Gtk.HSeparator hseparator9;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EliAssaltoAnfibio.EliOptions
			this.Events = ((global::Gdk.EventMask)(8192));
			this.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.Name = "EliAssaltoAnfibio.EliOptions";
			this.Title = "EliOptions";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(12));
			this.AllowShrink = true;
			// Container child EliAssaltoAnfibio.EliOptions.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "label1";
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator7 = new global::Gtk.HSeparator ();
			this.hseparator7.Name = "hseparator7";
			this.vbox7.Add (this.hseparator7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hseparator7]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.HeightRequest = 40;
			this.hbox6.Name = "hbox6";
			this.hbox6.Homogeneous = true;
			// Container child hbox6.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.TooltipMarkup = "INSERISCI IL NOMINATIVO DELL\'ELICOTTERO ";
			this.button1.WidthRequest = 250;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = "IDENTIFICATIVO ELICOTTERO";
			this.hbox6.Add (this.button1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.hbox6.Add (this.entry1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entry1]));
			w5.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = "ACCETTARE IL VALORE INSERITO";
			this.hbox6.Add (this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label4]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox7.Add (this.hbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox6]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add (this.vbox7);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox7]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox3.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.HeightRequest = 40;
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.TooltipMarkup = "INSERISCI CATEGORIA ELI (1 LEGGERO, 2 PESANTE, 3 ALTRO)";
			this.button2.WidthRequest = 250;
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = "CATEGORIA ELICOTTERO";
			this.hbox1.Add (this.button2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hscale1 = new global::Gtk.HScale (null);
			this.hscale1.CanFocus = true;
			this.hscale1.Name = "hscale1";
			this.hscale1.Adjustment.Lower = 1D;
			this.hscale1.Adjustment.Upper = 3D;
			this.hscale1.Adjustment.PageIncrement = 10D;
			this.hscale1.Adjustment.StepIncrement = 1D;
			this.hscale1.Adjustment.Value = 1D;
			this.hscale1.DrawValue = true;
			this.hscale1.Digits = 0;
			this.hscale1.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox1.Add (this.hscale1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hscale1]));
			w12.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = "ACCETTARE IL VALORE INSERITO";
			this.hbox1.Add (this.label5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label5]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox5.Add (this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox1]));
			w14.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.vbox5.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator5]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.HeightRequest = 40;
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.TooltipMarkup = "INSERISCI PESO CARBURANTE";
			this.button3.WidthRequest = 250;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = "PESO CARBURANTE ";
			this.hbox2.Add (this.button3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button3]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hscale2 = new global::Gtk.HScale (null);
			this.hscale2.CanFocus = true;
			this.hscale2.Name = "hscale2";
			this.hscale2.Adjustment.Lower = 450D;
			this.hscale2.Adjustment.Upper = 5000D;
			this.hscale2.Adjustment.PageIncrement = 10D;
			this.hscale2.Adjustment.StepIncrement = 1D;
			this.hscale2.Adjustment.Value = 456D;
			this.hscale2.DrawValue = true;
			this.hscale2.Digits = 0;
			this.hscale2.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox2.Add (this.hscale2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hscale2]));
			w17.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = "ACCETTARE IL VALORE INSERITO";
			this.hbox2.Add (this.label6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label6]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox3.Add (this.vbox5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox3.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator3]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.HeightRequest = 40;
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.TooltipMarkup = "INSERISCI PESO TOTALE DELLE TRUPPE IMBARCABILI";
			this.button5.WidthRequest = 250;
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = "PESO TRUPPE IMBARCABILI";
			this.hbox4.Add (this.button5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button5]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hscale4 = new global::Gtk.HScale (null);
			this.hscale4.CanFocus = true;
			this.hscale4.Name = "hscale4";
			this.hscale4.Adjustment.Upper = 4000D;
			this.hscale4.Adjustment.PageIncrement = 10D;
			this.hscale4.Adjustment.StepIncrement = 1D;
			this.hscale4.Adjustment.Value = 2D;
			this.hscale4.DrawValue = true;
			this.hscale4.Digits = 0;
			this.hscale4.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox4.Add (this.hscale4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hscale4]));
			w24.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = "ACCETTARE IL VALORE INSERITO";
			this.hbox4.Add (this.label8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label8]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.vbox6.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator6]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Homogeneous = true;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button13 = new global::Gtk.Button ();
			this.button13.TooltipMarkup = "INSERISCI PESO TOTALE DEL CARGO IMBARCABILE";
			this.button13.WidthRequest = 250;
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseUnderline = true;
			this.button13.Label = "PESO CARGO IMBARCABILE";
			this.hbox11.Add (this.button13);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button13]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hscale5 = new global::Gtk.HScale (null);
			this.hscale5.CanFocus = true;
			this.hscale5.Name = "hscale5";
			this.hscale5.Adjustment.Upper = 4000D;
			this.hscale5.Adjustment.PageIncrement = 10D;
			this.hscale5.Adjustment.StepIncrement = 1D;
			this.hscale5.Adjustment.Value = 14D;
			this.hscale5.DrawValue = true;
			this.hscale5.Digits = 0;
			this.hscale5.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox11.Add (this.hscale5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.hscale5]));
			w29.Position = 1;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = "ACCETTARE IL VALORE INSERITO";
			this.hbox11.Add (this.label3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label3]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox11.Add (this.hbox11);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox11]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hseparator11 = new global::Gtk.HSeparator ();
			this.hseparator11.Name = "hseparator11";
			this.vbox11.Add (this.hseparator11);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hseparator11]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Homogeneous = true;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button14 = new global::Gtk.Button ();
			this.button14.TooltipMarkup = "INSERISCI PESO MASSIMO AL DECOLLO";
			this.button14.WidthRequest = 250;
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseUnderline = true;
			this.button14.Label = "PESO MASSIMO AL DECOLLO";
			this.hbox12.Add (this.button14);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button14]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hscale6 = new global::Gtk.HScale (null);
			this.hscale6.CanFocus = true;
			this.hscale6.Name = "hscale6";
			this.hscale6.Adjustment.Lower = 1000D;
			this.hscale6.Adjustment.Upper = 25000D;
			this.hscale6.Adjustment.PageIncrement = 10D;
			this.hscale6.Adjustment.StepIncrement = 1D;
			this.hscale6.DrawValue = true;
			this.hscale6.Digits = 0;
			this.hscale6.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox12.Add (this.hscale6);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.hscale6]));
			w34.Position = 1;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = "ACCETTARE IL VALORE INSERITO";
			this.hbox12.Add (this.label11);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label11]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox11.Add (this.hbox12);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox12]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox6.Add (this.vbox11);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vbox11]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox6]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox4.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator4]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.HeightRequest = 40;
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.TooltipMarkup = "INSERISCI PESO ELICOTTERO SCARICO";
			this.button6.WidthRequest = 250;
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Relief = ((global::Gtk.ReliefStyle)(1));
			this.button6.Label = "PESO ELICOTTERO SCARICO";
			this.hbox5.Add (this.button6);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.button6]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hscale7 = new global::Gtk.HScale (null);
			this.hscale7.CanFocus = true;
			this.hscale7.Name = "hscale7";
			this.hscale7.Adjustment.Lower = 1000D;
			this.hscale7.Adjustment.Upper = 15000D;
			this.hscale7.Adjustment.PageIncrement = 10D;
			this.hscale7.Adjustment.StepIncrement = 1D;
			this.hscale7.Adjustment.Value = 1016D;
			this.hscale7.DrawValue = true;
			this.hscale7.Digits = 0;
			this.hscale7.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox5.Add (this.hscale7);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hscale7]));
			w41.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = "ACCETTARE IL VALORE INSERITO";
			this.hbox5.Add (this.label9);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label9]));
			w42.Position = 2;
			w42.Fill = false;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator13 = new global::Gtk.HSeparator ();
			this.hseparator13.Name = "hseparator13";
			this.vbox4.Add (this.hseparator13);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator13]));
			w44.Position = 3;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Homogeneous = true;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.TooltipMarkup = "INSERISCI IL CONSUMO DI CARBURANTE / ORA";
			this.button4.WidthRequest = 250;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = "CONSUMO CARB/H";
			this.hbox9.Add (this.button4);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button4]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hscale3 = new global::Gtk.HScale (null);
			this.hscale3.CanFocus = true;
			this.hscale3.Name = "hscale3";
			this.hscale3.Adjustment.Lower = 150D;
			this.hscale3.Adjustment.Upper = 1500D;
			this.hscale3.Adjustment.PageIncrement = 10D;
			this.hscale3.Adjustment.StepIncrement = 1D;
			this.hscale3.Adjustment.Value = 156D;
			this.hscale3.DrawValue = true;
			this.hscale3.Digits = 0;
			this.hscale3.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox9.Add (this.hscale3);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hscale3]));
			w46.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = "ACCETTARE IL VALORE INSERITO";
			this.hbox9.Add (this.label10);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label10]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			this.vbox4.Add (this.hbox9);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
			w48.Position = 4;
			w48.Expand = false;
			w48.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Homogeneous = true;
			this.vbox10.Spacing = -10;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hseparator12 = new global::Gtk.HSeparator ();
			this.hseparator12.Name = "hseparator12";
			this.vbox10.Add (this.hseparator12);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hseparator12]));
			w49.Position = 0;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.HeightRequest = 35;
			this.hbox7.Name = "hbox7";
			this.hbox7.Homogeneous = true;
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.WidthRequest = 600;
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button ();
			this.button10.TooltipMarkup = "POSIZIONE IN HANGAR O SUL PONTE";
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = "HANGAR";
			this.hbox3.Add (this.button10);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button10]));
			w50.Position = 0;
			w50.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button15 = new global::Gtk.Button ();
			this.button15.TooltipMarkup = "ELI A PALE APERTE O CHIUSE";
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.button15.Label = "PALE CHIUSE";
			this.hbox3.Add (this.button15);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button15]));
			w51.Position = 1;
			w51.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button16 = new global::Gtk.Button ();
			this.button16.TooltipMarkup = "ELI ACCESO O SPENTO";
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			this.button16.UseUnderline = true;
			this.button16.Label = "SPENTO";
			this.hbox3.Add (this.button16);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button16]));
			w52.Position = 2;
			w52.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button17 = new global::Gtk.Button ();
			this.button17.TooltipMarkup = "ELI EFFICIENTE O INEFFICIENTE";
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			this.button17.UseUnderline = true;
			this.button17.Label = "EFFICIENTE";
			this.hbox3.Add (this.button17);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button17]));
			w53.Position = 3;
			w53.Expand = false;
			this.hbox7.Add (this.hbox3);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox3]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			this.vbox10.Add (this.hbox7);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox7]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hseparator10 = new global::Gtk.HSeparator ();
			this.hseparator10.Name = "hseparator10";
			this.vbox10.Add (this.hseparator10);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hseparator10]));
			w56.Position = 2;
			w56.Expand = false;
			w56.Fill = false;
			this.vbox4.Add (this.vbox10);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox10]));
			w57.Position = 5;
			w57.Expand = false;
			w57.Fill = false;
			this.vbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
			w58.Position = 2;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.HeightRequest = 60;
			this.hbox8.CanDefault = true;
			this.hbox8.CanFocus = true;
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 56;
			this.hbox8.BorderWidth = ((uint)(4));
			// Container child hbox8.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = "PRECEDENTE";
			global::Gtk.Image w59 = new global::Gtk.Image ();
			w59.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.button8.Image = w59;
			this.hbox8.Add (this.button8);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button8]));
			w60.Position = 0;
			w60.Expand = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button11 = new global::Gtk.Button ();
			this.button11.TooltipMarkup = "SALVA IL RECORD CORRENTE, VEIRFICA I DATI INSERITI CON IL PULSANTE DI ACCETTAZION" +
			"E";
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.Label = "SALVA RECORD E RESETTA";
			this.hbox8.Add (this.button11);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button11]));
			w61.Position = 1;
			w61.Expand = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button ();
			this.button9.TooltipMarkup = "ACCETTA I DATI E TORNA AL MENU PRINCIPALE PER L\'IMMISSIONE DI ALTRE SPECIFICHE";
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.BorderWidth = ((uint)(3));
			this.button9.Label = "ACCETTA DATI - TORNA AL MENU PRINCIPALE";
			this.hbox8.Add (this.button9);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button9]));
			w62.Position = 2;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button12 = new global::Gtk.Button ();
			this.button12.TooltipMarkup = "CANCELLA IL RECORD CORRENTE";
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.Label = "ELIMINA RECORD";
			this.hbox8.Add (this.button12);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button12]));
			w63.Position = 3;
			w63.Expand = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = "SUCCESSIVO";
			global::Gtk.Image w64 = new global::Gtk.Image ();
			w64.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.button7.Image = w64;
			this.hbox8.Add (this.button7);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button7]));
			w65.PackType = ((global::Gtk.PackType)(1));
			w65.Position = 4;
			w65.Expand = false;
			this.vbox9.Add (this.hbox8);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox8]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hseparator9 = new global::Gtk.HSeparator ();
			this.hseparator9.Name = "hseparator9";
			this.vbox9.Add (this.hseparator9);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hseparator9]));
			w67.Position = 1;
			w67.Expand = false;
			w67.Fill = false;
			this.vbox8.Add (this.vbox9);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox9]));
			w68.Position = 0;
			w68.Expand = false;
			w68.Fill = false;
			this.vbox1.Add (this.vbox8);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox8]));
			w69.Position = 3;
			w69.Expand = false;
			w69.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1370;
			this.DefaultHeight = 677;
			this.hbox8.HasDefault = true;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button1.Released += new global::System.EventHandler (this.OnButton1Released);
			this.button2.Released += new global::System.EventHandler (this.OnButton2Released);
			this.button3.Released += new global::System.EventHandler (this.OnButton3Released);
			this.button5.Released += new global::System.EventHandler (this.OnButton5Released);
			this.button13.Released += new global::System.EventHandler (this.OnButton13Released);
			this.button14.Released += new global::System.EventHandler (this.OnButton14Released);
			this.button6.Released += new global::System.EventHandler (this.OnButton6Released);
			this.button4.Released += new global::System.EventHandler (this.OnButton4Released);
			this.button10.Released += new global::System.EventHandler (this.OnButton10Released);
			this.button15.Released += new global::System.EventHandler (this.OnButton15Released);
			this.button16.Released += new global::System.EventHandler (this.OnButton16Released);
			this.button17.Released += new global::System.EventHandler (this.OnButton17Released);
			this.button8.Released += new global::System.EventHandler (this.OnButton8Released);
			this.button11.Released += new global::System.EventHandler (this.OnButton11Released);
			this.button9.Released += new global::System.EventHandler (this.OnButton9Released);
			this.button12.Released += new global::System.EventHandler (this.OnButton12Released);
			this.button7.Released += new global::System.EventHandler (this.OnButton7Released);
		}
	}
}
