
// This file has been generated by the GUI designer. Do not modify.
namespace EliAssaltoAnfibio
{
	public partial class SpotOptions
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label1;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label2;
		private global::Gtk.CheckButton checkbutton7;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.CheckButton checkbutton1;
		private global::Gtk.CheckButton checkbutton2;
		private global::Gtk.CheckButton checkbutton3;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label4;
		private global::Gtk.HBox hbox6;
		private global::Gtk.CheckButton checkbutton4;
		private global::Gtk.CheckButton checkbutton5;
		private global::Gtk.CheckButton checkbutton6;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button button2;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Button button4;
		private global::Gtk.Button button5;
		private global::Gtk.Button button6;
		private global::Gtk.Button button3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EliAssaltoAnfibio.SpotOptions
			this.Name = "EliAssaltoAnfibio.SpotOptions";
			this.Title = "SpotOptions";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child EliAssaltoAnfibio.SpotOptions.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "Record #";
			this.vbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 150;
			this.label2.Name = "label2";
			this.label2.LabelProp = "EFFICIENZA SPOT";
			this.hbox5.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.checkbutton7 = new global::Gtk.CheckButton ();
			this.checkbutton7.TooltipMarkup = "EFFICIENZA SPOT";
			this.checkbutton7.CanFocus = true;
			this.checkbutton7.Name = "checkbutton7";
			this.checkbutton7.Label = "EFFICIENTE";
			this.checkbutton7.DrawIndicator = true;
			this.checkbutton7.UseUnderline = true;
			this.hbox5.Add (this.checkbutton7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.checkbutton7]));
			w3.Position = 1;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 150;
			this.label3.Name = "label3";
			this.label3.Xpad = 13;
			this.label3.LabelProp = "OPERAZIONI DIURNE";
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.TooltipMarkup = "LO SPOT E\' FUNZIONALE PER OPERAZIONI DIURNE ED ELICOTTERI DI CAT 1";
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = "ELICOTTERO LEGGERO";
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.hbox4.Add (this.checkbutton1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.checkbutton1]));
			w8.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.checkbutton2 = new global::Gtk.CheckButton ();
			this.checkbutton2.TooltipMarkup = "LO SPOT E\' FUNZIONALE PER OPERAZIONI DIURNE ED ELICOTTERI DI CAT 2";
			this.checkbutton2.CanFocus = true;
			this.checkbutton2.Name = "checkbutton2";
			this.checkbutton2.Label = "ELICOTTERO PESANTE";
			this.checkbutton2.DrawIndicator = true;
			this.checkbutton2.UseUnderline = true;
			this.hbox4.Add (this.checkbutton2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.checkbutton2]));
			w9.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.checkbutton3 = new global::Gtk.CheckButton ();
			this.checkbutton3.TooltipMarkup = "LO SPOT E\' FUNZIONALE PER OPERAZIONI DIURNE ED ELICOTTERI DI CAT 3";
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = "ALTRO";
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.hbox4.Add (this.checkbutton3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.checkbutton3]));
			w10.Position = 2;
			this.hbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
			w11.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox2.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator2]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 150;
			this.label4.Name = "label4";
			this.label4.Xpad = 6;
			this.label4.LabelProp = "OPERAZIONI NOTTURNE";
			this.hbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.checkbutton4 = new global::Gtk.CheckButton ();
			this.checkbutton4.TooltipMarkup = "LO SPOT E\' FUNZIONALE PER OPERAZIONI NOTTURNE ED ELICOTTERI DI CAT 1";
			this.checkbutton4.CanFocus = true;
			this.checkbutton4.Name = "checkbutton4";
			this.checkbutton4.Label = "ELICOTTERO LEGGERO";
			this.checkbutton4.DrawIndicator = true;
			this.checkbutton4.UseUnderline = true;
			this.hbox6.Add (this.checkbutton4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.checkbutton4]));
			w15.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.checkbutton5 = new global::Gtk.CheckButton ();
			this.checkbutton5.TooltipMarkup = "LO SPOT E\' FUNZIONALE PER OPERAZIONI NOTTURNE ED ELICOTTERI DI CAT 2";
			this.checkbutton5.CanFocus = true;
			this.checkbutton5.Name = "checkbutton5";
			this.checkbutton5.Label = "ELICOTTERO PESANTE";
			this.checkbutton5.DrawIndicator = true;
			this.checkbutton5.UseUnderline = true;
			this.hbox6.Add (this.checkbutton5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.checkbutton5]));
			w16.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.checkbutton6 = new global::Gtk.CheckButton ();
			this.checkbutton6.TooltipMarkup = "LO SPOT E\' FUNZIONALE PER OPERAZIONI NOTTURNE ED ELICOTTERI DI CAT 3";
			this.checkbutton6.CanFocus = true;
			this.checkbutton6.Name = "checkbutton6";
			this.checkbutton6.Label = "ALTRO";
			this.checkbutton6.DrawIndicator = true;
			this.checkbutton6.UseUnderline = true;
			this.hbox6.Add (this.checkbutton6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.checkbutton6]));
			w17.Position = 2;
			this.hbox2.Add (this.hbox6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox6]));
			w18.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox4.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator3]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.HeightRequest = 60;
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = "RECORD PRECEDENTE";
			this.hbox3.Add (this.button2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button2]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = "ACCETTA DATI - TORNA AL MENU PRINCIPALE";
			this.hbox7.Add (this.button4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button4]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = "SALVA RECORD";
			this.hbox7.Add (this.button5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button5]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = "ELIMINA RECORD";
			this.hbox7.Add (this.button6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button6]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox3.Add (this.hbox7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox7]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = "RECORD SUCCESSIVO";
			this.hbox3.Add (this.button3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button3]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 830;
			this.DefaultHeight = 239;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button2.Released += new global::System.EventHandler (this.OnButton2Released);
			this.button4.Released += new global::System.EventHandler (this.OnButton4Released);
			this.button5.Released += new global::System.EventHandler (this.OnButton5Released);
			this.button6.Released += new global::System.EventHandler (this.OnButton6Released);
			this.button3.Released += new global::System.EventHandler (this.OnButton3Released);
		}
	}
}
