
// This file has been generated by the GUI designer. Do not modify.
namespace EliAssaltoAnfibio
{
	public partial class InfoWindow
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label label6;
		private global::Gtk.HSeparator hseparator6;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EliAssaltoAnfibio.InfoWindow
			this.Name = "EliAssaltoAnfibio.InfoWindow";
			this.Title = "InfoWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child EliAssaltoAnfibio.InfoWindow.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = "INFORMATION WINDOW";
			this.vbox7.Add (this.label6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.vbox7.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hseparator6]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.BorderWidth = ((uint)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.textview1.AcceptsTab = false;
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
			this.textview1.PixelsAboveLines = 5;
			this.textview1.LeftMargin = 5;
			this.GtkScrolledWindow.Add (this.textview1);
			this.vbox7.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkScrolledWindow]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 2;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 633;
			this.DefaultHeight = 314;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
